### ISSUE TITLE
Multiply with white returns the non-white value

### ISSUE THREAD

**Issue by michaelurban** [loilo/color-blend#37]
If white with an alpha value is passed to `multiply` the non-white value is returned:

Multiply w\ white:
```
 {
  backdrop: { r: 255, g: 255, b: 255, a: 0.12 }, // White
  source: { r: 0, g: 107, b: 84, a: 1 }, // Non-White
  ret: { r: 0, g: 107, b: 84, a: 1 } // SAME Non-White Value
}
```

It works with a non-white `source` or `backdrop` value:

Multiply w\ non-white: 
```
{
  backdrop: { r: 0, g: 107, b: 84, a: 0.12 },
  source: { r: 251, g: 253, b: 250, a: 1 },
  ret: { r: 221, g: 235, b: 230, a: 1 }
}
```
Is this the expected behavior? I'm getting accurate results when multiplying non-white values.

```
const { multiply } = require("color-blend");

const colorWhiteAlpha12 = { r: 255, g: 255, b: 255, a: 0.12 };
const colorPrimary = { r: 0, g: 107, b: 84, a: 1 };

const colorSurface = { r: 251, g: 253, b: 250, a: 1 };
const colorPrimaryAlpha12 = { r: 0, g: 107, b: 84, a: 0.12 };

const colorPrimaryTint = multiply(colorWhiteAlpha12, colorPrimary);
const colorSurfaceTint = multiply(colorPrimaryAlpha12, colorSurface);

console.log("colorPrimaryTint: ", colorPrimaryTint);
console.log("colorSurfaceTint: ", colorSurfaceTint);

/* OUTPUT
colorPrimaryTint:  { r: 0, g: 107, b: 84, a: 1 } - Same as `colorPrimary`
colorSurfaceTint:  { r: 221, g: 235, b: 230, a: 1 }
*/

```

**Comment by loilo** [comment]
This is expected behavior. The Multiply mode does what the name says — it multiplies the RGB channels of the involved colors (on a scale from 0 to 1). So if you multiply any color with white (which has 1 for each color channel), the color will not change.

The alpha channel of neither of the colors has any influence on the resulting RGB channels. (In fact, it doesn't impact the RGB outcome in _any_ blend mode.)
I've got to say that this confused me as well when I implemented the color modes in the first place, but that's how the algorithms are designed – alpha channels of both the source and the backdrop only impact the alpha channel of the resulting color, nothing else.

Hope that helped.

**Comment by loilo** [comment]
True, reverse engineering this is almost impossible. But they're all abiding by [the spec](https://www.w3.org/TR/compositing-1/#blendingmultiply).

**Comment by loilo** [comment]
True. It's why I built the library in the first place. 😁 
That said, figuring out how opacity works with blend modes also was basically _the_ [biggest pain point](https://stackoverflow.com/questions/40796852/mix-two-non-opaque-colors-with-hue-blend-mode) when implementing this.

**Comment by loilo** [comment]
Everything the browser does is written down in specs somewhere. However, you need quite some practice and knowledge about their environment to successfully decipher them.

Regarding opacity: The point (that I could hardly even believe when I found out) is that the opacity is _irrelevant_ for the blending itself. All blend modes offered by this library use so-called "source-over" composition. (I say "offered by this library" because there are some new blend modes in the current iteration of the spec, and in part already in browsers, which don't use source-over composition and therefore work differently from everything done here, which is why I haven't implemented those yet.)

Back to topic: Using the source-over compositioning algorithm basically means that you first blend the RGB channels of the colors with the according blend mode algorithm (i.e. treat colors as if they all have full opacity) and only _then_ calculate the result's opacity from the foreground/background opacities.

Or in other words: The used colors' opacities have _no_ impact on the resulting color's RGB, only on its opacity. 🤯

**Comment by loilo** [comment]
Glad it's helping. Fun fact: I haven't used it, ever. 🙃
Built it because I wanted to try out if some basic version of Photoshop would be creatable in the browser (in 2015) and for some weird reason started with implementing blend modes — which is also the only thing I ever implemented for this project. 🙈
